name: Build and deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - .github/**

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test
  build-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the docker build-image
        run: docker build -t $DOCKERHUB_USERNAME/eventpro-api .
      - name: push to dockerhub
        run: docker push $DOCKERHUB_USERNAME/eventpro-api:latest
