name: Build and deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - .github/**

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test
  docker-build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Dockerhub
        run: docker login -u $DOCKERHUB_USERNAME --password-stdin $DOCKERHUB_PASSWORD
      - name: Build Docker Image
        run: docker build -t $DOCKERHUB_USERNAME/eventpro-api:latest .
      - name: Push Docker Image
        run: docker push $DOCKERHUB_USERNAME/eventpro-api:latest
